### ISSUE TITLE
[BUG] TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by officialdittaz** [phaticusthiccy/Open-APIs#37]
const instagram = require("@phaticusthiccy/open-apis");

async function start() {
    try{
    var data = await instagram.insta_reel("https://www.instagram.com/reel/CgZ-afJl5so/?igshid=YmMyMTA2M2Y=")
    console.log(data)
    } catch(err){
    console.log(err)
    }
}
start() 

TypeError: Cannot read property 'data' of undefined
    at Object.insta_reel (/home/runner/EXTREAM-BOTZ/node_modules/@phaticusthiccy/open-apis/InstaDownloader/start/instagram_reel.js:14:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async start (eval at module.exports (/home/runner/EXTREAM-BOTZ/message/msg.js:4481:20), <anonymous>:5:13)
    at async module.exports (/home/runner/EXTREAM-BOTZ/message/msg.js:4481:14)

**Comment by phaticusthiccy** [comment]
Seems needs to be work on it.. Lemme check
